### ISSUE TITLE
Collaborating on snow water equivalent estimation 

### ISSUE THREAD

**Issue by patwater** [hoargroup/stationsweRegression#1]
Please see here for our GitHub repo: https://github.com/California-Data-Collaborative/snowbot

Would love to find time to discuss and find collaboration opportunities!

**Comment by dschneiderch** [comment]
Hi Patrick,

I’m not really involved with this work any more but you might find some interest from Kehan who has taken over some of the work.

https://instaar.colorado.edu/people/kehan-yang/

Dominik

**Comment by patwater** [comment]
Great! By chance do you know Kehan's GitHub handle? If not I can just sent an email ping. Thanks much!

**Comment by dschneiderch** [comment]
@KehanGit
But not sure she really uses it.
